### ISSUE TITLE
Not working: Failed to execute 'observe' on 'MutationObserver'

### ISSUE THREAD

**Issue by gkrystev** [EvHaus/youtube-hide-watched#11]
Didn't use the script for a week, during that time the YouTube interface did change.
I saw that a new version of the plugin was issued, but today I noticed that the script do not hide the watched videos.

I got this error from the Chrome console.

Error running script: YouTube: Hide Watched Videos
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

**Comment by EvHaus** [comment]
Hmm. Not sure why that error would come up. In any case -- I pushed some updates in 2.3 that might help resolve the problem. Try again now.

**Comment by gkrystev** [comment]
The error do not appear anymore, but the watched videos are still not hidden. No any errors in the logs.
I noticed some strange behavior of the button on the top bar.
When you hover over it, it disappears while the mouse is over it instead to highlight or pop-up or something else. Also, when you click on it it disappears again, but it will appear only if you click somewhere else on the page. The state is switched between hide and show but with no effect.
Not sure how I can debug this further.

**Comment by EvHaus** [comment]
What version of Chrome are you using?

**Comment by EvHaus** [comment]
Fixed in 2.4
